name: sub4dart
description: A Subsonic API wrapper written in Dart.
# version: 1.0.0
# homepage: https://iceteacity.com
# author: lucas <lucas@iceteacity.com>

dependencies:
  crypto: ^2.0.6
  password_hash: ^2.0.0

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
